### ISSUE TITLE
regarding https://github.com/sajjadkarimi91/motor-imagery-BCI

### ISSUE THREAD

**Issue by srinathakuthota** [sajjadkarimi91/motor-imagery-BCI#1]
https://github.com/sajjadkarimi91/motor-imagery-BCI

sir thank you for us providing code and i have executed the code got successful i want to write research paper on it how can i proceed on it and also which section i can modify to improve the results ??

i want complete analysis on results we got kindly help us we are doing research on bci related to motor imagery

**Comment by sajjadkarimi91** [comment]
Hi 
This repository is the implementation of classic methods, and its 10-CV also must be changed to avoid minor leakage in training and testing feature extraction.
I will develop a new repository for the recent approach with an accurate 10-CV soon.
In my opinion, new ideas like the Riemannian Geometry approach must be developed from scratch to write a new research paper.

**Comment by srinathakuthota** [comment]
Sir thank you kindly help in suggesting to read the  best research papers
to implement the code and modifications which is must for me🙏🙏🙏🙏
