### ISSUE TITLE
motor-imagery-BCI

### ISSUE THREAD

**Issue by srinathakuthota** [sajjadkarimi91/motor-imagery-BCI#3]
sir kindly suggest the base paper to implement the classic method of motor imagery bci with improvement in accuracy as well kindly help in which section is modification can able to done easily .....please reply as soon as possible

**Comment by sajjadkarimi91** [comment]
Hi

I am very busy for next three weeks.
In the readme file, I introduced the base paper titled:
Filter bank common spatial pattern algorithm on BCI competition IV Datasets 2a and 2b

If there are any code bugs, please report them, and as I said before, these codes aren't suitable for a new research paper.

Thanks

**Comment by srinathakuthota** [comment]
Thank you for your email sir kindly send the code for Filter bank common
spatial pattern algorithm on BCI competition IV Datasets 2a and 2b
And i want to implement the research paper with github code provided by you
sir and i want improvement in preprocessing stage so kindly provide
improved accuracy or any other parameters related code


🙏🙏🙏🙏

**Comment by srinathakuthota** [comment]
sir,whether we can use the code with your permission would you give the permission to improve the code and run in matlab

**Comment by srinathakuthota** [comment]
kindly reply at your earliest convenience rime

**Comment by sajjadkarimi91** [comment]
> sir,whether we can use the code with your permission would you give the permission to improve the code and run in matlab

You can use the code and modify the code for your research goals.
